py_test(
    name = "test_get_specifications",
    srcs = ["test_get_specifications.py"],
    deps = [
        "//cli/bitcode:commands",
        "//cli/common:service_configuration_handler",
        "//cli/eesi:commands",
        "//cli/eesi:domain_knowledge_handler",
        "//cli/eesi:synonym_configuration_handler",
        "//cli/test/common",
    ],
)
