py_test(
    name = "test_called_functions",
    size = "small",
    srcs = ["test_called_functions.py"],
    deps = [
        "//cli/bitcode:commands",
        "//cli/common:service_configuration_handler",
        "//cli/test/common",
    ],
)

py_test(
    name = "test_local_called_functions",
    size = "small",
    srcs = ["test_local_called_functions.py"],
    deps = [
        "//cli/bitcode:commands",
        "//cli/common:service_configuration_handler",
        "//cli/test/common",
    ],
)

py_test(
    name = "test_file_called_functions",
    size = "small",
    srcs = ["test_file_called_functions.py"],
    deps = [
        "//cli/bitcode:commands",
        "//cli/common:service_configuration_handler",
        "//cli/test/common",
    ],
)

py_test(
    name = "test_defined_functions",
    size = "small",
    srcs = ["test_defined_functions.py"],
    deps = [
        "//cli/bitcode:commands",
        "//cli/common:service_configuration_handler",
        "//cli/test/common",
    ],
)

py_test(
    name = "test_register_bitcode",
    size = "small",
    srcs = ["test_register_bitcode.py"],
    deps = [
        "//cli/bitcode:commands",
        "//cli/common:service_configuration_handler",
        "//cli/test/common",
    ],
)
