py_library(
    name = "db",
    srcs = ["db.py"],
    visibility = [
        "//cli/bitcode:__pkg__",
        "//cli/checker:__pkg__",
        "//cli/eesi:__pkg__",
        "//cli/embedding:__pkg__",
        "//cli/getgraph:__pkg__",
    ],
)
