py_library(
    name = "operations",
    srcs = ["operations.py"],
    visibility = [
        "//cli/bitcode:__pkg__",
        "//cli/checker:__pkg__",
        "//cli/eesi:__pkg__",
        "//cli/embedding:__pkg__",
        "//cli/getgraph:__pkg__",
    ],
    deps = [
        "//proto:operations_py_grpc",
    ],
)

py_library(
    name = "wait",
    srcs = ["wait.py"],
    visibility = [
        "//cli/bitcode:__pkg__",
        "//cli/checker:__pkg__",
        "//cli/eesi:__pkg__",
        "//cli/embedding:__pkg__",
        "//cli/getgraph:__pkg__",
        "//cli/walker:__pkg__",
    ],
)
